spring.application.name=Recando-dos-Passaros

# Configuração de Conexão com o MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/cafeteria-bd?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# Driver do MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Porta do Servidor
server.port=8080