spring.application.name=Recando-dos-Passaros

#  AQUI ONDE EU GUARDO AS INFORMAÇÕES PARA CONECTAR CCOM O BANCO
pring.application.name=spring-data-mySQL
spring.datasource.url=jdbc:mysql://localhost:3306/cafeteria_bd
spring.datasource.username=${USERNAME}
spring.datasource.password.=${PASSWORD}

#sicroniza o java com o banco
# se crio uma classe tabela no java adiciona automaticamnte
spring.jpa.hibernate.ddl-auto=update 


spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# mostra quando criamos as queries
spring.jpa.show-sql=true
#formata o texto da queries
spring.jpa.properties.hibernate.format_sql=true
server.port=8080